#logging settings
log:
  filename: /Users/sw/go/log/kd-microservice.log.log
  level: DEBUG

#database settings
database:
  hostname: ${DB_HOST}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  uri: ${DB_URI}

#server settings
server:
  port: 5600
  env: prd
  log-output: console
  output-file-path: ./kd-microservice.log
  config-path: .
  service-name: kd-microservice

#Access Control SETTING
access-control:
  allow-origin: "*"
  allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allow-credentials: "true"
  allow-headers: "Origin, Content-Type, Authorization"
  request-headers: "Origin, Content-Type, Authorization"

url:
  base-url-s3: ${S3_BASE_URI}

#source type available
source-type: [
  hospital,
  article,
  doctor
]

route:
  site: "/rating-svc"
  apiprefix: "/api/v1"

thumbor:
  base_url: https://img-cdn.medkomtek.com 
  format_image: smart/filters:quality(75):strip_icc():format(webp)
  secret: ${THUMBOR_SECRET}
  size_large_screen: "48 x 48"
  size_small_screen:  "32 x 32"

util:
  timezone: Asia/Jakarta
