#logging settings
log:
  filename: /Users/sw/go/log/gitlab.smartfren.com/example-api/example-api.log
  level: DEBUG

#database settings
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: jiren1411
  schema: testong
