#logging settings
log:
  filename: /Users/sw/go/log/kd-microservice.log.log
  level: DEBUG

#database settings
database:
  driver: ${db.driver}
  hostname: ${db.host}
  port: ${db.port}
  username: ${db.username}
  password: ${db.password}
  dbname: ${db.schema}
