#logging settings
log:
  filename: /Users/sw/go/log/kd-microservice.log.log
  level: DEBUG

#database settings
database:
  driver: ${DB_DRIVER}
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}

server:
  port: 5600
  env: dev
  log-output: console
  output-file-path: ./kd-microservice.log
  config-path: .
  service-name: kd-microservice
