#logging settings
log:
  filename: /Users/sw/go/log/kd-microservice.log.log
  level: DEBUG

#database settings
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: jiren1411
  schema: testong
