definitions:
  BaseIDModel:
    properties:
      is_deleted:
        type: boolean
        x-go-name: IsDeleted
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
        x-go-name: UID
    type: object
    x-go-package: gokit_example/pkg/entity
  ErrorResponse:
    properties:
      code:
        description: |-
          Code of the business code
          in: int64
        format: int64
        type: integer
        x-go-name: Code
      data:
        description: |-
          Message of the respons
          in: string
        type: object
        x-go-name: Data
      message:
        description: |-
          Message of the respons
          in: int64
        type: string
        x-go-name: Message
    type: object
    x-go-name: ErrorResponseHttp
    x-go-package: gokit_example/pkg/entity
  SuccessResponse:
    properties:
      code:
        description: |-
          Code of the business code
          in: int64
        format: int64
        type: integer
        x-go-name: Code
      data:
        description: |-
          Message of the respons
          in: string
        type: object
        x-go-name: Data
      message:
        description: |-
          Message of the respons
          in: int64
        type: string
        x-go-name: Message
    type: object
    x-go-name: ResponseHttp
    x-go-package: gokit_example/pkg/entity
  product:
    properties:
      is_deleted:
        type: boolean
        x-go-name: IsDeleted
      name:
        description: |-
          Name of the product
          in: string
        type: string
        x-go-name: Name
      sku:
        description: |-
          Sku of the product
          in: string
        type: string
        x-go-name: Sku
      uid:
        description: |-
          UID of the product
          in: int64
        type: string
        x-go-name: UID
      uom:
        description: |-
          Uom of the product
          in: string
        type: string
        x-go-name: Uom
      weight:
        description: |-
          Weight of the product
          in: int32
        format: int32
        type: integer
        x-go-name: Weight
    type: object
    x-go-name: Product
    x-go-package: gokit_example/pkg/entity
paths:
  /prescription/product/:
    post:
      description: Create product
      operationId: product
      parameters:
      - description: 'name: Name'
        in: body
        name: name
        required: true
        schema:
          type: string
        x-go-name: Name
      - description: 'name: Sku'
        in: body
        name: sku
        required: true
        schema:
          type: string
        x-go-name: Sku
      - description: 'name: Uom'
        in: body
        name: uom
        required: true
        schema:
          type: string
        x-go-name: Uom
      - description: 'name: Weight'
        in: body
        name: weight
        required: true
        schema:
          format: int32
          type: integer
        x-go-name: Weight
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - apiKey:
        - '[]'
      tags:
      - prescription
  /prescription/product/{id}:
    get:
      description: Get product
      operationId: getProduct
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - apiKey:
        - '[]'
      tags:
      - prescription
    put:
      description: Get product
      operationId: update_product
      parameters:
      - description: 'name: id'
        in: path
        name: id
        required: true
        type: string
        x-go-name: Id
      - description: |-
          Name of the Product
          in: string
          name: Name
        in: formData
        name: name
        required: true
        type: string
        x-go-name: Name
      - description: 'name: Sku'
        in: body
        name: sku
        required: true
        schema:
          type: string
        x-go-name: Sku
      - description: 'name: Uom'
        in: body
        name: uom
        required: true
        schema:
          type: string
        x-go-name: Uom
      - description: 'name: Weight'
        in: body
        name: weight
        required: true
        schema:
          format: int32
          type: integer
        x-go-name: Weight
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - apiKey:
        - '[]'
      tags:
      - prescription
  /prescription/products/:
    get:
      description: Get product lists
      operationId: productList
      responses:
        "200":
          description: SuccessResponse
          schema:
            $ref: '#/definitions/SuccessResponse'
        "401":
          description: ErrorResponse
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - apiKey:
        - '[]'
      tags:
      - prescription
swagger: "2.0"
