package response

// swagger:model UploadResponse
type UploadResponse struct {
	UID string	`json:"uid"`
	MediaPath string `json:"media_path"`
}

type ResponseHttpMedia struct {
	Meta MetaMedia `json:"meta"`
	Data DataMedia `json:"data"`
}

type ImageFilesData struct {
	Uid string `json:"uid"`
	Url string `json:"url"`
	AutoGenerated bool `json:"auto_generated"`
	Status string `json:"status"`
	ImageProfileUid string `json:"image_profile_uid"`
	ImageProfileName string `json:"image_profile_name"`
	ImageProfileCode string `json:"image_profile_code"`
	MediaFileName string `json:"media_file_name"`
	MediaContentType string `json:"media_content_type"`
	MediaFileSize int64 `json:"media_file_size"`
	MediaPath string `json:"media_path"`
}

type DataMedia struct {
	Record RecordMediaFile `json:"record"`
}

type MetaMedia struct {
	Code int64 `json:"code"`
	Message string `json:"message"`
}
type RecordMediaFile struct {
	Uid string `json:"uid"`
	Name string `json:"name"`
	MediaCategoryUid string `json:"media_category_uid"`
	MediaCategoryName string `json:"media_category_name"`
	ImageFiles []ImageFilesData `json:"image_files"`
	Description string `json:"description"`
}